name: test-2

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]

jobs:
  test-2:
    runs-on: windows-11-arm64

    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "Don't mind me, just running this test workflow"
